// Re-export des erreurs depuis @gen3ia/core
export {
  ApiError,
  NotFoundError, UnauthorizedError, ForbiddenError,
  ValidationError, RateLimitError,
  AgentError,
  AgentTimeoutError, AgentMaxIterationsError, AgentLoopDetectedError,
  LLMError, ToolNotAllowedError,
  PaymentError,
  InsufficientCreditsError, PaymentFailedError, StripeError,
  MobileMoneyError, PlanLimitReachedError,
  AuthError,
  SessionExpiredError, InvalidTokenError, OAuthError,
  InvalidCredentialsError,
  AgentSafetyError,
  SandboxViolationError, PromptInjectionError, ResourceExceededError,
  WebhookError,
  InvalidSignatureError, ReplayDetectedError,
  DatabaseError, UniqueConstraintError,
  handleApiError, ErrorCodes,
  ApiResponse, ApiSuccessResponse, ApiErrorResponse,
} from '../../packages/core/src/errors';
