"use client";
import { useEffect, useRef, useState } from "react";
import { type User } from "firebase/auth";
import { watchAuth } from "@/lib/firebase/client";
import { authFetch, useSessionAvailable } from "@/lib/firebase/auth-client";

export default function StoragePage() {
  const [user, setUser] = useState<User | null>(null); const [files, setFiles] = useState<Array<{ path: string; filename: string; sizeBytes: number }>>([]); const [requests, setRequests] = useState<Array<{ id: string; reason: string; facingMode: string }>>([]); const [busy, setBusy] = useState(false); const videoRef = useRef<HTMLVideoElement>(null);
  const sessionDisponible = useSessionAvailable();
  const refresh = async () => { const [f, r] = await Promise.all([authFetch("/api/storage/permanent", { cache: "no-store" }), authFetch("/api/camera/requests", { cache: "no-store" })]); if (f.ok) setFiles((await f.json()).files ?? []); if (r.ok) setRequests((await r.json()).requests ?? []); };
  useEffect(() => { void refresh(); return watchAuth(current => { setUser(current); }); }, []);
  const upload = async (file: File) => { if (sessionDisponible === false) return; setBusy(true); try { const form = new FormData(); form.append("file", file); const response = await authFetch("/api/storage/permanent", { method: "POST", body: form }); if (!response.ok) throw new Error((await response.json()).error); await refresh(); } finally { setBusy(false); } };
  const capture = async (requestId: string, facingMode: "user" | "environment") => { if (sessionDisponible === false || !videoRef.current) return; setBusy(true); try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode } }); videoRef.current.srcObject = stream; await videoRef.current.play(); await new Promise(r => setTimeout(r, 800)); const canvas = document.createElement("canvas"); canvas.width = videoRef.current.videoWidth; canvas.height = videoRef.current.videoHeight; canvas.getContext("2d")?.drawImage(videoRef.current, 0, 0); stream.getTracks().forEach(t => t.stop()); const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob(b => b ? resolve(b) : reject(new Error("Camera capture failed")), "image/jpeg", .92)); const response = await authFetch(`/api/camera/complete`, { method: "POST", headers: { "content-type": "image/jpeg", "x-camera-request-id": requestId }, body: blob }); if (!response.ok) throw new Error((await response.json()).error); await refresh(); } finally { setBusy(false); } };
  return <div className="min-h-full bg-[#f6f4ef] text-neutral-900 p-6"><div className="mx-auto max-w-6xl"><h1 className="font-serif text-3xl font-bold">Stockage permanent</h1><p className="mt-2 text-neutral-500">Vos fichiers restent associés à votre compte. Les agents peuvent les lire et les manipuler uniquement selon leurs permissions.</p><div className="mt-6 rounded-3xl border border-[rgba(23,23,20,0.09)] bg-white p-6 shadow-[0_2px_10px_rgba(15,23,42,0.05)]"><label className="inline-flex cursor-pointer rounded-full bg-neutral-900 px-5 py-3 font-semibold text-white hover:bg-neutral-800"><input type="file" className="hidden" disabled={busy} onChange={e => e.target.files?.[0] && upload(e.target.files[0])}/>Importer un fichier</label><div className="mt-6 space-y-2">{files.map(file => <div key={file.path} className="flex items-center justify-between rounded-xl border border-neutral-200 p-4"><span>{file.filename}</span><span className="text-xs text-neutral-500">{(file.sizeBytes / 1024).toFixed(1)} KB</span></div>)}{!files.length && <p className="text-sm text-neutral-400">Aucun fichier permanent.</p>}</div></div><div className="mt-6 rounded-3xl border border-[rgba(23,23,20,0.09)] bg-white p-6 shadow-[0_2px_10px_rgba(15,23,42,0.05)]"><h2 className="font-serif text-xl font-semibold">Demandes caméra des agents</h2><p className="mt-2 text-sm text-neutral-500">La caméra n’est jamais activée silencieusement. Une demande d’agent doit être acceptée par l’utilisateur et expire automatiquement.</p><video ref={videoRef} className="mt-4 hidden w-full max-w-xl rounded-xl" playsInline muted /> <div className="mt-5 space-y-3">{requests.map(r => <div key={r.id} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="text-sm">{r.reason}</p><button disabled={busy} onClick={() => capture(r.id, r.facingMode === "user" ? "user" : "environment")} className="mt-3 rounded-full bg-emerald-600 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-500">Autoriser et prendre la photo</button></div>)}{!requests.length && <p className="text-sm text-neutral-400">Aucune demande en attente.</p>}</div></div></div></div>;
}
