import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { prompt, language, agentId } = await request.json();
    if (!prompt) return NextResponse.json({ error: "Prompt requis" }, { status: 400 });
    const lang = language || "ts";
    const header = "// Generated by Genova AI Agent\n// " + new Date().toISOString() + "\n\n";
    const tpl = {
      ts: header + "export function process(input: string): string {\n  return `Result: ${input}`;\n}\n",
      tsx: header + "export default function C() {\n  return <div>Genova</div>;\n}\n",
      py: header + "def process(data):\n    return {'status': 'ok'}\n",
      js: header + "module.exports = { handler: (r) => r.json({ ok: true }) };\n",
    };
    return NextResponse.json({ success: true, code: tpl[lang] || header + "// Generated\n", language: lang, lines: (tpl[lang] || header).split("\n").length });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : "Erreur" }, { status: 500 });
  }
}
