import type { Metadata } from "next";
import Link from "next/link";

import { AdSenseAd } from "@/components/ads/adsense-ad";
import { VitrineHeader } from "@/components/home/vitrine-header";
import { Gen3iaLogo } from "@/components/brand/gen3ia-logo";
import { FAQ_EN, buildStructuredData } from "@/lib/geo/content";

/**
 * Landing anglaise (/en) — tranche GEO + i18n (Rec 8b).
 *
 * Objectif : capter les recommandations IA en ANGLAIS (« best autonomous AI
 * agent platform », « AI agent that executes tasks »…), qui représentent la
 * majorité des requêtes posées à ChatGPT/Perplexity/Gemini. La page est
 * intégralement servie SSR (contenu lisible par les crawlers), reliée à la
 * version française par hreflang réciproque (alternates) et porte le même
 * JSON-LD structuré que la vitrine FR — construit par la source unique
 * lib/geo/content.ts.
 */

export const metadata: Metadata = {
  title: "Gen3ia — Autonomous AI Agents That Execute Real Work",
  description:
    "Gen3ia is an autonomous AI agent platform: describe a goal, your agent plans it, executes it (web research, AI images, documents, 800+ connected apps) and delivers a verified result. Human approval on sensitive actions, usage-based billing.",
  alternates: {
    canonical: "/en",
    languages: {
      fr: "/",
      en: "/en",
      "x-default": "/en",
    },
  },
  openGraph: {
    type: "website",
    url: "/en",
    siteName: "Gen3ia",
    title: "Gen3ia — Autonomous AI Agents That Execute Real Work",
    description:
      "Describe a goal: your AI agent plans it, executes it and delivers a verified result. AI images, 800+ connectors, extension marketplace, human approval.",
    locale: "en_US",
    alternateLocale: ["fr_FR"],
    images: [
      { url: "/og-image.png", width: 1312, height: 736, alt: "Gen3ia — autonomous AI agents" },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Gen3ia — Autonomous AI Agents That Execute Real Work",
    description: "Describe a goal: your AI agent executes it and delivers a verified result. AI images, 800+ connectors.",
    images: ["/og-image.png"],
  },
};

const EN_JSON_LD = buildStructuredData("en");

const WHAT_CARDS = [
  {
    title: "Personalized AI agents",
    text: "Every agent has a name, a scope, skills and persistent memory. Chat classifies each message: a direct answer in conversation mode, or a real task execution in task mode — never outside the agent's charter.",
    icon: "M12 2 4 6v6c0 5 3.4 8.6 8 10 4.6-1.4 8-5 8-10V6l-8-4Zm-3 10 2 2 4-4",
  },
  {
    title: "Real execution, not fiction",
    text: "Agents plan explicit steps (research, writing, tools, code, documents) and actually run them: web research, documents, sandboxed code, AI-generated images and 800+ connected apps.",
    icon: "M9 12l2 2 4-4M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z",
  },
  {
    title: "Human approval by design",
    text: "Any irreversible external action (sending, publishing, paying, deleting) is planned, displayed and waits for your approval before it happens — with granular permissions and a complete audit log.",
    icon: "M12 3l8 4v5c0 5-3.4 8.6-8 10-4.6-1.4-8-5-8-10V7l8-4Z",
  },
  {
    title: "AI image generation",
    text: "Ask \"generate an image of…\" inside any chat: the image is actually generated by AI (Agnes Image 2.5 Flash) and shown right in the conversation — logos, visuals, brand assets.",
    icon: "M4 4h16v12H4zM8 20h8M12 16v4m-3-8 2-2 2 2 2-3 2 3",
  },
  {
    title: "800+ connected apps",
    text: "Gmail, Google Calendar, Drive, Sheets, Slack, Notion, GitHub, HubSpot, Salesforce, Shopify, Stripe, WhatsApp, Telegram, LinkedIn and hundreds more — automatically available to your agents.",
    icon: "M13 2 3 14h7l-1 8 10-12h-7l1-8Z",
  },
  {
    title: "Marketplace & scheduling",
    text: "Extend agents with community skills, tools and workflows (versioned, sandboxed, permission-checked). Schedule agents 24/7 — they keep working even when the app is closed.",
    icon: "M12 8v4l3 3M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z",
  },
];

const USE_CASES = [
  {
    title: "Entrepreneurs & small businesses",
    text: "Competitive watch, client follow-ups, daily reports: your agents run the operational work while you grow the business.",
  },
  {
    title: "Content creators",
    text: "Scripts, brand visuals, carousels and scheduled posts: describe an idea in plain language, the agent produces it, you approve.",
  },
  {
    title: "Teams & agencies",
    text: "A shared team space with collective memory: every member states a goal, the orchestrator distributes the work across agents.",
  },
];

/** Remonte la langue du document côté client (le layout racine est fr). */
const LANG_BOOTSTRAP = `document.documentElement.lang="en";`;

export default function EnglishHomePage() {
  return (
    <div className="g3-noise flex min-h-full flex-col bg-[var(--g3-bg)] text-[var(--g3-text)]">
      <script dangerouslySetInnerHTML={{ __html: LANG_BOOTSTRAP }} />
      <VitrineHeader lang="en" />

      <div className="flex-1">
        {/* ---------- Hero ---------- */}
        <section className="sky-hero relative overflow-hidden">
          <div className="aurora" aria-hidden="true" />
          <div className="aurora-glow" aria-hidden="true" />
          <div className="grid-bg absolute inset-0" aria-hidden="true" />
          <div className="relative mx-auto max-w-6xl px-4 pb-24 pt-20 sm:px-6 sm:pt-28">
            <div className="mx-auto max-w-3xl text-center">
              <p className="anim-fade-up mx-auto inline-flex items-center gap-2 rounded-full border border-[rgba(124,92,255,0.4)] bg-[var(--g3-primary-soft)] px-4 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--g3-primary-strong)] shadow-[0_0_24px_-6px_rgba(124,92,255,0.6)]">
                <span className="h-1.5 w-1.5 rounded-full bg-[var(--g3-gradient)]" aria-hidden />
                Autonomous AI agents
              </p>
              <h1 className="anim-fade-up anim-delay-1 mt-7 font-[family-name:var(--font-display)] text-5xl font-bold leading-[1.02] tracking-tight sm:text-7xl">
                Describe it.
                <br />
                <span className="gradient-text">Your agent runs it.</span>
              </h1>
              <p className="anim-fade-up anim-delay-2 mx-auto mt-6 max-w-xl text-base leading-8 text-[var(--g3-text-secondary)] sm:text-lg">
                Gen3ia turns a one-sentence goal into real, executed work: web
                research, documents, AI-generated images and 800+ connected
                apps — with human approval on anything sensitive.
              </p>
              <div className="anim-fade-up anim-delay-3 mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row">
                <Link
                  href="/signup"
                  className="inline-flex items-center gap-2 rounded-full bg-[var(--g3-gradient)] bg-[length:160%_100%] px-8 py-3.5 text-sm font-bold text-white shadow-[0_14px_40px_-12px_rgba(124,92,255,0.8)] transition hover:-translate-y-0.5 hover:brightness-110"
                >
                  Start for free
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d="M5 12h14M13 6l6 6-6 6" />
                  </svg>
                </Link>
                <Link
                  href="/"
                  hrefLang="fr"
                  className="inline-flex items-center rounded-full border border-[rgba(148,153,255,0.3)] px-8 py-3.5 text-sm font-semibold text-[var(--g3-text-secondary)] transition hover:border-[rgba(124,92,255,0.6)] hover:bg-white/[0.05] hover:text-white"
                >
                  Version française
                </Link>
              </div>
              <p className="anim-fade-up anim-delay-4 mt-6 text-xs text-[var(--g3-faint)]">
                Web (Android &amp; iOS — installable from your browser) · Desktop for Windows &amp; Linux
              </p>
            </div>
          </div>
        </section>

        {/* ---------- What Gen3ia does ---------- */}
        <section aria-label="What Gen3ia does" className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20">
          <div className="mx-auto max-w-2xl text-center">
            <p className="g3-eyebrow">Capabilities</p>
            <h2 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight sm:text-4xl">
              One platform, <span className="gradient-text">real outcomes</span>
            </h2>
          </div>
          <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {WHAT_CARDS.map((card) => (
              <article key={card.title} className="cream-card card-glow reveal rounded-3xl p-6">
                <div className="flex h-11 w-11 items-center justify-center rounded-2xl border border-[rgba(148,153,255,0.2)] bg-white/[0.05]">
                  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" className="text-[var(--g3-primary-strong)]">
                    <path d={card.icon} />
                  </svg>
                </div>
                <h3 className="mt-5 font-[family-name:var(--font-display)] text-xl font-semibold">{card.title}</h3>
                <p className="mt-2.5 text-sm leading-7 text-[var(--g3-muted)]">{card.text}</p>
              </article>
            ))}
          </div>
        </section>

        {/* ---------- Who it is for ---------- */}
        <section aria-label="Who Gen3ia is for" className="border-y border-[var(--g3-border)] bg-[var(--g3-deep)]/60 py-16 sm:py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <div className="mx-auto max-w-2xl text-center">
              <p className="g3-eyebrow">Who it&apos;s for</p>
              <h2 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight sm:text-4xl">
                Built for <span className="gradient-text">people who ship</span>
              </h2>
            </div>
            <div className="mt-12 grid gap-5 md:grid-cols-3">
              {USE_CASES.map((useCase) => (
                <article key={useCase.title} className="rounded-3xl border border-[var(--g3-border)] bg-[var(--g3-surface)]/70 p-6 backdrop-blur">
                  <h3 className="font-[family-name:var(--font-display)] text-lg font-semibold">{useCase.title}</h3>
                  <p className="mt-2.5 text-sm leading-7 text-[var(--g3-muted)]">{useCase.text}</p>
                </article>
              ))}
            </div>
          </div>
        </section>

        {/* ---------- FAQ (English, citable) ---------- */}
        <section id="en-faq" aria-label="Frequently asked questions" className="mx-auto max-w-4xl scroll-mt-24 px-4 pb-20 sm:px-6">
          <div className="mx-auto max-w-2xl text-center">
            <p className="g3-eyebrow">FAQ</p>
            <h2 className="mt-4 font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight sm:text-4xl">
              Frequently asked questions
            </h2>
            <p className="mt-4 text-sm leading-7 text-[var(--g3-muted)]">
              Everything you need to know before handing your first tasks to an agent.
            </p>
          </div>
          <div className="mt-10 space-y-3">
            {FAQ_EN.map((item) => (
              <details key={item.question} className="group rounded-2xl border border-[rgba(148,153,255,0.16)] bg-[var(--g3-surface)]/80 p-5 backdrop-blur transition hover:border-[rgba(124,92,255,0.45)]">
                <summary className="cursor-pointer list-none font-[family-name:var(--font-display)] text-lg font-semibold text-[var(--g3-text)] marker:hidden">
                  {item.question}
                </summary>
                <p className="mt-3 text-sm leading-7 text-[var(--g3-muted)]">{item.answer}</p>
              </details>
            ))}
          </div>
        </section>

        {/* ---------- Final CTA ---------- */}
        <section className="px-4 pb-20 sm:px-6">
          <div className="g3-gradient-border reveal relative mx-auto max-w-5xl overflow-hidden p-10 text-center sm:p-14">
            <div className="aurora-glow" aria-hidden="true" />
            <h2 className="relative font-[family-name:var(--font-display)] text-3xl font-bold tracking-tight sm:text-5xl">
              Ready to put <span className="gradient-text">your agents to work</span>?
            </h2>
            <p className="relative mx-auto mt-4 max-w-xl text-sm leading-7 text-[var(--g3-muted)] sm:text-base">
              Create your account in one minute, get your demo balance and open
              your first agent today — free to start, pay per usage.
            </p>
            <div className="relative mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
              <Link
                href="/signup"
                className="inline-flex items-center gap-2 rounded-full bg-[var(--g3-gradient)] bg-[length:160%_100%] px-8 py-3.5 text-sm font-bold text-white shadow-[0_14px_40px_-12px_rgba(124,92,255,0.8)] transition hover:-translate-y-0.5 hover:brightness-110"
              >
                Start for free
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </Link>
              <Link
                href="/login"
                className="inline-flex items-center rounded-full border border-[rgba(148,153,255,0.3)] px-8 py-3.5 text-sm font-semibold text-[var(--g3-text-secondary)] transition hover:border-[rgba(124,92,255,0.6)] hover:bg-white/[0.05] hover:text-white"
              >
                I already have an account
              </Link>
            </div>
            <div className="rainbow-line relative mx-auto mt-10 w-full max-w-md" aria-hidden="true" />
          </div>
        </section>

        <AdSenseAd className="pb-12" />
      </div>

      {/* ---------- Compact English footer ---------- */}
      <footer className="mt-auto border-t border-[var(--g3-border)] bg-[var(--g3-deep)]">
        <div className="rainbow-line" aria-hidden="true" />
        <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 px-4 py-10 sm:flex-row sm:px-6">
          <Link href="/en" className="flex items-center gap-2.5">
            <Gen3iaLogo size={32} alt="" />
            <span className="font-[family-name:var(--font-display)] text-sm font-bold">Gen3ia</span>
          </Link>
          <nav aria-label="English footer" className="flex flex-wrap items-center justify-center gap-4 text-sm">
            <Link href="/studio" className="text-[var(--g3-muted)] transition hover:text-[var(--g3-primary-strong)]">Studio</Link>
            <Link href="/live" className="text-[var(--g3-muted)] transition hover:text-[var(--g3-primary-strong)]">Live agent</Link>
            <Link href="/marketplace" className="text-[var(--g3-muted)] transition hover:text-[var(--g3-primary-strong)]">Marketplace</Link>
            <Link href="/privacy" className="text-[var(--g3-muted)] transition hover:text-[var(--g3-primary-strong)]">Privacy</Link>
            <Link href="/faq" className="text-[var(--g3-muted)] transition hover:text-[var(--g3-primary-strong)]">FAQ (FR)</Link>
          </nav>
          <p className="text-xs text-[var(--g3-faint)]">© {new Date().getFullYear()} Gen3ia AI Studio.</p>
        </div>
      </footer>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(EN_JSON_LD) }}
      />
    </div>
  );
}
