/**
 * Registre des endpoints OAuth réels des applications populaires.
 *
 * Chaque entrée est un endpoint PUBLIC et STABLE, documenté par le
 * fournisseur (developer docs). Combiné aux identifiants de client
 * enregistrés par l'opérateur (OAuthAppConfig / variables d'environnement),
 * ce registre rend la connexion « un clic → autoriser » possible pour
 * l'utilisateur final — qui ne voit jamais un jeton.
 *
 * L'opérateur peut étendre ce registre à TOUTE app du catalogue via
 * l'interface d'administration (saisie des endpoints + client_id/secret).
 */

export interface OAuthEndpointEntry {
  /** URL d'autorisation (redirection utilisateur). */
  authorizeUrl: string
  /** URL d'échange du code → jetons. */
  tokenUrl: string
  /** URL de rafraîchissement (souvent = tokenUrl). */
  refreshUrl?: string
  /** URL de révocation (RFC 7009, si publiée). */
  revokeUrl?: string
  /** Profil utilisateur (vérification de la connexion). */
  userInfoUrl?: string
  /** Scopes par défaut de la plateforme. */
  scope: string
  /** PKCE (S256) obligatoire ou recommandé. */
  usePkce: boolean
  /** En-tête d'authentification des requêtes API. */
  authStyle: "bearer" | "query_token" | "basic"
  /** Paramètre query pour le jeton (authStyle = query_token). */
  tokenQueryParam?: string
  /** En-têtes statiques additionnels des requêtes API. */
  apiHeaders?: Record<string, string>
  /** URL de base des requêtes API. */
  baseUrl: string
  /** Documentation développeur publique. */
  docsUrl: string
}

export const OAUTH_ENDPOINTS: Record<string, OAuthEndpointEntry> = {
  github: {
    authorizeUrl: "https://github.com/login/oauth/authorize",
    tokenUrl: "https://github.com/login/oauth/access_token",
    userInfoUrl: "https://api.github.com/user",
    scope: "read:user user:email repo",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.github.com",
    docsUrl: "https://docs.github.com/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps",
  },
  gitlab: {
    authorizeUrl: "https://gitlab.com/oauth/authorize",
    tokenUrl: "https://gitlab.com/oauth/token",
    userInfoUrl: "https://gitlab.com/api/v4/user",
    scope: "read_user read_api",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://gitlab.com/api/v4",
    docsUrl: "https://docs.gitlab.com/ee/api/oauth2.html",
  },
  bitbucket: {
    authorizeUrl: "https://bitbucket.org/site/oauth2/authorize",
    tokenUrl: "https://bitbucket.org/site/oauth2/access_token",
    userInfoUrl: "https://api.bitbucket.org/2.0/user",
    scope: "account repository",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.bitbucket.org/2.0",
    docsUrl: "https://developer.atlassian.com/cloud/bitbucket/rest/oauth2/",
  },
  slack: {
    authorizeUrl: "https://slack.com/oauth/v2/authorize",
    tokenUrl: "https://slack.com/api/oauth.v2.access",
    refreshUrl: "https://slack.com/api/oauth.v2.access",
    userInfoUrl: "https://slack.com/api/auth.test",
    scope: "chat:write channels:read channels:history users:read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://slack.com/api",
    docsUrl: "https://api.slack.com/authentication/oauth-v2",
  },
  discord: {
    authorizeUrl: "https://discord.com/oauth2/authorize",
    tokenUrl: "https://discord.com/api/oauth2/token",
    userInfoUrl: "https://discord.com/api/users/@me",
    scope: "identify email guilds messages.read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://discord.com/api/v10",
    docsUrl: "https://discord.com/developers/docs/topics/oauth2",
  },
  notion: {
    authorizeUrl: "https://api.notion.com/v1/oauth/authorize",
    tokenUrl: "https://api.notion.com/v1/oauth/token",
    userInfoUrl: "https://api.notion.com/v1/users/me",
    scope: "read content update insert",
    usePkce: true,
    authStyle: "bearer",
    apiHeaders: { "Notion-Version": "2022-06-28" },
    baseUrl: "https://api.notion.com/v1",
    docsUrl: "https://developers.notion.com/docs/authorization",
  },
  linear: {
    authorizeUrl: "https://linear.app/oauth/authorize",
    tokenUrl: "https://api.linear.app/oauth/token",
    userInfoUrl: "https://api.linear.app/graphql",
    scope: "read write issues:create",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.linear.app",
    docsUrl: "https://developers.linear.app/oauth/authentication",
  },
  airtable: {
    authorizeUrl: "https://airtable.com/oauth2/v1/authorize",
    tokenUrl: "https://airtable.com/oauth2/v1/token",
    userInfoUrl: "https://api.airtable.com/v0/meta/whoami",
    scope: "data.records:read data.records:write",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.airtable.com/v0",
    docsUrl: "https://airtable.com/developers/web/api/oauth-reference",
  },
  asana: {
    authorizeUrl: "https://app.asana.com/-/oauth_authorize",
    tokenUrl: "https://app.asana.com/-/oauth_token",
    userInfoUrl: "https://app.asana.com/api/1.0/users/me",
    scope: "default",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://app.asana.com/api/1.0",
    docsUrl: "https://developers.asana.com/docs/oauth",
  },
  trello: {
    // Trello : OAuth1 (3-legged) documenté.
    authorizeUrl: "https://trello.com/1/authorize",
    tokenUrl: "https://trello.com/1/OAuthGetAccessToken",
    scope: "read write",
    usePkce: false,
    authStyle: "query_token",
    tokenQueryParam: "key",
    baseUrl: "https://api.trello.com/1",
    docsUrl: "https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/",
  },
  jira: {
    authorizeUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    refreshUrl: "https://auth.atlassian.com/oauth/token",
    userInfoUrl: "https://api.atlassian.com/me",
    scope: "read:jira-user read:jira-work write:jira-work offline_access",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.atlassian.com/ex/jira",
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-guides/",
  },
  confluence: {
    authorizeUrl: "https://auth.atlassian.com/authorize",
    tokenUrl: "https://auth.atlassian.com/oauth/token",
    refreshUrl: "https://auth.atlassian.com/oauth/token",
    userInfoUrl: "https://api.atlassian.com/me",
    scope: "read:confluence-user read:confluence-content.space write:confluence-content offline_access",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.atlassian.com/ex/confluence",
    docsUrl: "https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-guides/",
  },
  monday: {
    authorizeUrl: "https://auth.monday.com/oauth2/authorize",
    tokenUrl: "https://auth.monday.com/oauth2/token",
    scope: "me boards:read boards:write",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.monday.com/v2",
    docsUrl: "https://developer.monday.com/apps/docs/oauth",
  },
  clickup: {
    authorizeUrl: "https://app.clickup.com/api",
    tokenUrl: "https://api.clickup.com/api/v2/oauth/token",
    userInfoUrl: "https://api.clickup.com/api/v2/user",
    scope: "",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.clickup.com/api/v2",
    docsUrl: "https://developer.clickup.com/docs/authentication",
  },
  pipedrive: {
    authorizeUrl: "https://oauth.pipedrive.com/oauth/authorize",
    tokenUrl: "https://oauth.pipedrive.com/oauth/token",
    scope: "deals:read deals:write contacts:read contacts:write",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.pipedrive.com/v1",
    docsUrl: "https://developers.pipedrive.com/docs/api/authentication/oauth",
  },
  hubspot: {
    authorizeUrl: "https://app.hubspot.com/oauth/authorize",
    tokenUrl: "https://api.hubapi.com/oauth/v1/token",
    refreshUrl: "https://api.hubapi.com/oauth/v1/token",
    userInfoUrl: "https://api.hubapi.com/oauth/v2/v3/access-tokens/",
    scope: "crm.objects.contacts.read crm.objects.contacts.write crm.objects.deals.read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.hubapi.com",
    docsUrl: "https://developers.hubspot.com/docs/api/oauth/quickstart",
  },
  salesforce: {
    authorizeUrl: "https://login.salesforce.com/services/oauth2/authorize",
    tokenUrl: "https://login.salesforce.com/services/oauth2/token",
    refreshUrl: "https://login.salesforce.com/services/oauth2/token",
    userInfoUrl: "https://login.salesforce.com/services/oauth2/userinfo",
    scope: "api refresh_token offline_access",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://login.salesforce.com/services/data/v59.0",
    docsUrl: "https://help.salesforce.com/s/articleView?id=xcloud.remoteaccess_oauth_flows.htm",
  },
  zendesk: {
    authorizeUrl: "https://{subdomain}.zendesk.com/oauth/authorizations/new",
    tokenUrl: "https://{subdomain}.zendesk.com/oauth/tokens",
    scope: "read write",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://{subdomain}.zendesk.com/api/v2",
    docsUrl: "https://developer.zendesk.com/documentation/api/ticketing/oauth/using-oauth-authentication/",
  },
  intercom: {
    authorizeUrl: "https://app.intercom.com/oauth",
    tokenUrl: "https://api.intercom.io/auth/eagle/token",
    scope: "admin",
    usePkce: false,
    authStyle: "bearer",
    apiHeaders: { Accept: "application/json", "Intercom-Version": "2.11" },
    baseUrl: "https://api.intercom.io",
    docsUrl: "https://developers.intercom.com/building-apps/docs/oauth-reference",
  },
  figma: {
    authorizeUrl: "https://www.figma.com/oauth",
    tokenUrl: "https://www.figma.com/api/oauth/token",
    userInfoUrl: "https://api.figma.com/v1/me",
    scope: "file_read",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.figma.com/v1",
    docsUrl: "https://www.figma.com/developers/api#access-tokens",
  },
  dropbox: {
    authorizeUrl: "https://www.dropbox.com/oauth2/authorize",
    tokenUrl: "https://api.dropboxapi.com/oauth2/token",
    userInfoUrl: "https://api.dropboxapi.com/2/users/get_current_account",
    scope: "files.content.read files.content.write account_info.read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.dropboxapi.com/2",
    docsUrl: "https://www.dropbox.com/developers/documentation/http/documentation",
  },
  box: {
    authorizeUrl: "https://account.box.com/api/oauth2/authorize",
    tokenUrl: "https://api.box.com/oauth2/token",
    refreshUrl: "https://api.box.com/oauth2/token",
    userInfoUrl: "https://api.box.com/2.0/users/me",
    scope: "",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.box.com/2.0",
    docsUrl: "https://developer.box.com/guides/authentication/oauth2/",
  },
  googledrive: {
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/oauth2/v3/userinfo",
    scope: "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.profile",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://www.googleapis.com/drive/v3",
    docsUrl: "https://developers.google.com/identity/protocols/oauth2/web-server",
  },
  googlesheets: {
    authorizeUrl: "https://accounts.google.com/o/oauth2/v2/auth",
    tokenUrl: "https://oauth2.googleapis.com/token",
    userInfoUrl: "https://www.googleapis.com/oauth2/v3/userinfo",
    scope: "https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.profile",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://sheets.googleapis.com/v4",
    docsUrl: "https://developers.google.com/sheets/api/guides/authorizing",
  },
  zoom: {
    authorizeUrl: "https://zoom.us/oauth/authorize",
    tokenUrl: "https://zoom.us/oauth/token",
    refreshUrl: "https://zoom.us/oauth/token",
    userInfoUrl: "https://api.zoom.us/v2/users/me",
    scope: "meeting:read:admin meeting:write:admin user:read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.zoom.us/v2",
    docsUrl: "https://developers.zoom.us/docs/guides/build-oauth-app/",
  },
  calendly: {
    authorizeUrl: "https://auth.calendly.com/oauth/authorize",
    tokenUrl: "https://auth.calendly.com/oauth/token",
    userInfoUrl: "https://api.calendly.com/users/me",
    scope: "",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.calendly.com",
    docsUrl: "https://developer.calendly.com/api-docs/oauth-migration",
  },
  docusign: {
    authorizeUrl: "https://account.docusign.com/oauth/auth",
    tokenUrl: "https://account.docusign.com/oauth/token",
    refreshUrl: "https://account.docusign.com/oauth/token",
    userInfoUrl: "https://account.docusign.com/oauth/userinfo",
    scope: "signature",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://demo.docusign.net/restapi/v2.1",
    docsUrl: "https://developers.docusign.com/platform/auth/authcode/",
  },
  mailchimp: {
    authorizeUrl: "https://login.mailchimp.com/oauth2/authorize",
    tokenUrl: "https://login.mailchimp.com/oauth2/token",
    userInfoUrl: "https://login.mailchimp.com/oauth2/metadata",
    scope: "",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://{dc}.api.mailchimp.com/3.0",
    docsUrl: "https://mailchimp.com/developer/marketing/guides/access-mailchimp-with-oauth-2/",
  },
  typeform: {
    authorizeUrl: "https://authorization.typeform.com/oauth/authorize",
    tokenUrl: "https://authorization.typeform.com/oauth/token",
    scope: "forms:read forms:write responses:read",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.typeform.com",
    docsUrl: "https://www.typeform.com/developers/create/oauth-applications/",
  },
  surveymonkey: {
    authorizeUrl: "https://api.surveymonkey.com/oauth/authorize",
    tokenUrl: "https://api.surveymonkey.com/oauth/token",
    scope: "surveys_read surveys_write responses_read",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.surveymonkey.com/v3",
    docsUrl: "https://developer.surveymonkey.com/api/v3/oauth2/",
  },
  twitter: {
    authorizeUrl: "https://x.com/i/oauth2/authorize",
    tokenUrl: "https://api.twitter.com/2/oauth2/token",
    refreshUrl: "https://api.twitter.com/2/oauth2/token",
    userInfoUrl: "https://api.twitter.com/2/users/me",
    scope: "tweet.read tweet.write users.read offline.access",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.twitter.com/2",
    docsUrl: "https://docs.x.com/resources/fundamentals/authentication/oauth-2-0/authorization-code",
  },
  linkedin: {
    authorizeUrl: "https://www.linkedin.com/oauth/v2/authorization",
    tokenUrl: "https://www.linkedin.com/oauth/v2/accessToken",
    userInfoUrl: "https://api.linkedin.com/v2/userinfo",
    scope: "openid profile email r_liteprofile w_member_social",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.linkedin.com/v2",
    docsUrl: "https://learn.microsoft.com/linkedin/shared/authentication/authorization-code-flow",
  },
  reddit: {
    authorizeUrl: "https://www.reddit.com/api/v1/authorize",
    tokenUrl: "https://www.reddit.com/api/v1/access_token",
    userInfoUrl: "https://oauth.reddit.com/api/v1/me",
    scope: "identity read submit",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://oauth.reddit.com",
    docsUrl: "https://support.reddithelp.com/hc/en-us/articles/16160319875092",
  },
  spotify: {
    authorizeUrl: "https://accounts.spotify.com/authorize",
    tokenUrl: "https://accounts.spotify.com/api/token",
    userInfoUrl: "https://api.spotify.com/v1/me",
    scope: "user-read-email user-read-private playlist-modify-public",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.spotify.com/v1",
    docsUrl: "https://developer.spotify.com/documentation/web-api/tutorials/code-flow",
  },
  twitch: {
    authorizeUrl: "https://id.twitch.tv/oauth2/authorize",
    tokenUrl: "https://id.twitch.tv/oauth2/token",
    userInfoUrl: "https://api.twitch.tv/helix/users",
    scope: "user:read:email",
    usePkce: false,
    authStyle: "bearer",
    apiHeaders: { "Client-Id": "{client_id}" },
    baseUrl: "https://api.twitch.tv/helix",
    docsUrl: "https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/",
  },
  medium: {
    authorizeUrl: "https://medium.com/oauth/authorize",
    tokenUrl: "https://api.medium.com/v1/tokens",
    scope: "basicProfile publishPost",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.medium.com/v1",
    docsUrl: "https://github.com/Medium/medium-api-docs",
  },
  wordpress: {
    authorizeUrl: "https://public-api.wordpress.com/oauth2/authorize",
    tokenUrl: "https://public-api.wordpress.com/oauth2/token",
    userInfoUrl: "https://public-api.wordpress.com/rest/v1.1/me",
    scope: "posts:read posts:write",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://public-api.wordpress.com/rest/v1.1",
    docsUrl: "https://developer.wordpress.com/docs/oauth2/",
  },
  todoist: {
    authorizeUrl: "https://todoist.com/oauth/authorize",
    tokenUrl: "https://todoist.com/oauth/access_token",
    userInfoUrl: "https://api.todoist.com/api/v1/user",
    scope: "data:read_write",
    usePkce: true,
    authStyle: "bearer",
    baseUrl: "https://api.todoist.com/api/v1",
    docsUrl: "https://todoist.com/developers/docs#authorization",
  },
  harvest: {
    authorizeUrl: "https://id.getharvest.com/oauth2/authorize",
    tokenUrl: "https://id.getharvest.com/api/v2/oauth2/token",
    userInfoUrl: "https://api.harvestapp.com/v2/users/me",
    scope: "all",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.harvestapp.com/v2",
    docsUrl: "https://www.getharvest.com/developers",
  },
  smartsheet: {
    authorizeUrl: "https://app.smartsheet.com/b/authorize",
    tokenUrl: "https://app.smartsheet.com/api/v2/oauth/token",
    scope: "READ_SHEETS WRITE_SHEETS",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.smartsheet.com/2.0",
    docsUrl: "https://smartsheet.redoc.ly/",
  },
  basecamp: {
    authorizeUrl: "https://launchpad.37signals.com/authorization/new",
    tokenUrl: "https://launchpad.37signals.com/authorization/token",
    userInfoUrl: "https://launchpad.37signals.com/authorization.json",
    scope: "",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://3.basecampapi.com",
    docsUrl: "https://github.com/basecamp/api/blob/master/sections/authentication.md",
  },
  quickbooks: {
    authorizeUrl: "https://appcenter.intuit.com/connect/oauth2",
    tokenUrl: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
    refreshUrl: "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
    userInfoUrl: "https://sandbox-quickbooks.api.intuit.com/v3/company/{company_id}/companyinfo/{company_id}",
    scope: "com.intuit.quickbooks.accounting",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://quickbooks.api.intuit.com/v3",
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0",
  },
  xero: {
    authorizeUrl: "https://login.xero.com/identity/connect/authorize",
    tokenUrl: "https://identity.xero.com/connect/token",
    refreshUrl: "https://identity.xero.com/connect/token",
    userInfoUrl: "https://api.xero.com/connections",
    scope: "offline_access accounting.contacts accounting.transactions",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://api.xero.com/api.xro/2.0",
    docsUrl: "https://developer.xero.com/documentation/getting-started/getting-set-up",
  },
  stripe: {
    authorizeUrl: "https://connect.stripe.com/oauth/authorize",
    tokenUrl: "https://connect.stripe.com/oauth/token",
    userInfoUrl: "https://api.stripe.com/v1/account",
    scope: "read_write",
    usePkce: false,
    authStyle: "basic",
    baseUrl: "https://api.stripe.com/v1",
    docsUrl: "https://docs.stripe.com/stripe-apps/api-authentication/oauth",
  },
  shopify: {
    authorizeUrl: "https://{shop}.myshopify.com/admin/oauth/authorize",
    tokenUrl: "https://{shop}.myshopify.com/admin/oauth/access_token",
    scope: "read_products write_products read_orders",
    usePkce: false,
    authStyle: "query_token",
    tokenQueryParam: "access_token",
    baseUrl: "https://{shop}.myshopify.com/admin/api/2024-07",
    docsUrl: "https://shopify.dev/docs/apps/auth/oauth",
  },
  helpscout: {
    authorizeUrl: "https://secure.helpscout.net/authentication/authorize",
    tokenUrl: "https://secure.helpscout.net/authentication/token",
    scope: "conversations:read conversations:write",
    usePkce: false,
    authStyle: "bearer",
    baseUrl: "https://docsapi.helpscout.net/v1",
    docsUrl: "https://developer.helpscout.com/docs-api/authentication/",
  },
}

/** Renvoie les endpoints réels connus d'une app (ou null). */
export function getOAuthEndpoints(appSlug: string): OAuthEndpointEntry | null {
  return OAUTH_ENDPOINTS[appSlug] ?? null
}
