name: Deploy Firebase Rules

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Deploy rules
        run: bun run firestore:rules && bun run storage:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
