name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        type: environment
        required: true
        default: 'production'

jobs:
  deploy-vercel:
    name: Deploy to render
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v7
      - name: Deploy to render
        uses: amondnet/render-action@v42
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          render-org-id: ${{ secrets.RENDER_ORG_ID }}
          render-project-id: ${{ secrets.RENDER_PROJECT_ID }}
          render-args: '--prod'

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build Docker
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: gen3ia:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
